#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# for agnoster theme
DEFAULT_USER=jrusso
# aliases 
alias vim='nvim'
alias hockey='cd ~/code/GitHub/LazyMan && java -jar LazyMan.jar'
alias gst='git status'
# export ugrad='jrusso15@ugradx.cs.jhu.edu'

ugrad () {
    ssh jrusso15@ugrad${1}.cs.jhu.edu
}

# export VISUAL=nvim
# export EDITOR="$VISUAL"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

